### ISSUE TITLE
No logo was downloaded?

### ISSUE THREAD

**Issue by Lojalfan** [boppreh/steamgrid#87] opened 2021-03-02 21:55 UTC
For example: it downloaded Hero and Cover images for Prince of Persia but not the logo. Actually it didn't download the missing ones for any game. I tried with -styles "official" and the same without quotation marks.

**Comment by Lojalfan** [comment] 2021-03-04 14:07
None of the other fixes work for me. I've tried:

* Recompiling from the source code
* changing line 149 in download.go to only "filter := steamGridFilter"

**Comment by Lucki** [comment] 2021-03-20 12:38
Duplicate of #85

**Comment by Lucki** [comment] 2021-03-20 12:40
Steamgrid does not have a style named "official".

**Closed** 2021-03-27 16:20 UTC
